### ISSUE TITLE
ncurses (+pdcurses 3.x): demos with compiler warnings and one error

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#111]
Happening with ncurses 6.1, GCC 8.3.0 and ncurses 6.0, GCC 6.4.0:

~~~
../demos/testcurs.c: In function ‘acsTest’:
../demos/testcurs.c:1252:26: warning: unused variable ‘combining_marks’ [-Wunused-variable]
     static const wchar_t combining_marks[] = { L'C', L'o', 0x35c, L'm',
                          ^~~~~~~~~~~~~~~
../demos/testcurs.c:1249:26: warning: unused variable ‘fullwidth’ [-Wunused-variable]
     static const wchar_t fullwidth[] = { 0xff26, 0xff55, 0xff4c, 0xff4c,
                          ^~~~~~~~~
../demos/testcurs.c:1246:26: warning: unused variable ‘georgian’ [-Wunused-variable]
     static const wchar_t georgian[] = {0x10e5, 0x10d0, 0x10e0, 0x10d7,
                          ^~~~~~~~
../demos/testcurs.c:1243:26: warning: unused variable ‘greek’ [-Wunused-variable]
     static const wchar_t greek[] = {0x0395, 0x03bb, 0x03bb, 0x03b7,
                          ^~~~~
../demos/testcurs.c:1240:26: warning: unused variable ‘russian’ [-Wunused-variable]
     static const wchar_t russian[] = {0x0420, 0x0443, 0x0441, 0x0441,
                          ^~~~~~~
../demos/testcurs.c:1182:20: warning: unused variable ‘wacs_values’ [-Wunused-variable]
     const cchar_t *wacs_values[] =
                    ^~~~~~~~~~~
At top level:
../demos/testcurs.c:1240:26: warning: ‘russian’ defined but not used [-Wunused-const-variable=]
     static const wchar_t russian[] = {0x0420, 0x0443, 0x0441, 0x0441,
                          ^~~~~~~
../demos/testcurs.c:1243:26: warning: ‘greek’ defined but not used [-Wunused-const-variable=]
     static const wchar_t greek[] = {0x0395, 0x03bb, 0x03bb, 0x03b7,
                          ^~~~~
../demos/testcurs.c:1246:26: warning: ‘georgian’ defined but not used [-Wunused-const-variable=]
     static const wchar_t georgian[] = {0x10e5, 0x10d0, 0x10e0, 0x10d7,
                          ^~~~~~~~
../demos/testcurs.c:1249:26: warning: ‘fullwidth’ defined but not used [-Wunused-const-variable=]
     static const wchar_t fullwidth[] = { 0xff26, 0xff55, 0xff4c, 0xff4c,
                          ^~~~~~~~~
../demos/testcurs.c:1252:26: warning: ‘combining_marks’ defined but not used [-Wunused-const-variable=]
     static const wchar_t combining_marks[] = { L'C', L'o', 0x35c, L'm',
                          ^~~~~~~~~~~~~~~
cc -Wall -O3 -D_XOPEN_SOURCE_EXTENDED -oworm ../demos/worm.c -lncurses
cc -Wall -O3 -D_XOPEN_SOURCE_EXTENDED -oxmas ../demos/xmas.c -lncurses
cc -Wall -O3 -D_XOPEN_SOURCE_EXTENDED -otuidemo ../demos/tui.c ../demos/tuidemo.c -lncurses
../demos/tui.c: In function ‘colorbox’:
../demos/tui.c:146:9: warning: variable ‘maxx’ set but not used [-Wunused-but-set-variable]
     int maxx;
         ^~~~
../demos/tui.c: In function ‘bodylen’:
../demos/tui.c:445:15: warning: variable ‘maxx’ set but not used [-Wunused-but-set-variable]
     int maxy, maxx;
               ^~~~
../demos/tui.c: In function ‘repainteditbox’:
../demos/tui.c:719:9: warning: variable ‘maxy’ set but not used [-Wunused-but-set-variable]
     int maxy;
         ^~~~
~~~

Only happening with ncurses 6.0, GCC 6.4.0:

~~~
../demos/tui.c: In function 'weditstr':
../demos/tui.c:787:20: error: dereferencing pointer to incomplete type 'WINDOW {aka struct _win_st}'
     oldattr = wedit->_attrs;
                    ^~
~~~

Last part (solved with 7efcc5dd59a05c7ad02a50acef52bd2375bb94b7):
~~Doing a build with pdcurses 3.x the compiler complains about missing `A_STRIKEOUT` (should I add an ifdef guard around the single occurrence?) and multiple times about `A_OVERLINE` (I could check for the define and if not available define it to zero, as it is always part of a bitwise-or `|` this should make no difference).~~

What should be done about the other warnings and the single error?

**Comment by Bill-Gray** [comment]
Oddly,  I didn't get most of the warnings with GCC-8.3 or 9.1 on my Xubuntu 18.04 box.  But they showed up on the 19.04 box,  so I could replicate and fix the `testcurs.c` problem (plus warnings that showed up for `newtest.c` on GCC-9.1.)
`tui.c` presents the problem that `getmaxyx` is a macro.  You have to pass it both values;  only one gets used,  and the other gets you that unused variable warning.
And that error with ncurses 6.0 and GCC 6.4 is quite weird.  I don't have a way of replicating that.  I've never seen that error;  seems it comes up when the `struct` in question has been declared,  but not defined yet.

**Comment by GitMensch** [comment]
> tui.c presents the problem that getmaxyx is a macro [...]

One could work around this by using an unused "guard" (which only exists to not warn about unused items), if you like to check [`COB_UNUSED`](https://sourceforge.net/p/open-cobol/code/HEAD/tree/trunk/libcob/common.h#l600).

> And that error with ncurses 6.0 and GCC 6.4 is quite weird. I don't have a way of replicating that.

As this doesn't happen with newer GCC-versions (I assume you've rechecked that) and only with ncurses the solution seems to just add a comment in this line like "old ncurses/compilers may raise an error here". Or (which I'd suggest) add a version guard in the program's header, something like
```c
#if NCURSES_VERS == 600000
#error ncurses 6.0 is known to not work with this file, use a newer version
#endif
```

**Comment by Bill-Gray** [comment]
I think these are now completely fixed. The remaining bit was the GCC 6.4 one.  I don't have GCC 6.4,  but we're now accessing the attributes using `getattrs()` instead of directly accessing `WINDOW` structure members.
