### ISSUE TITLE
Changelog for 4.1?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#128]
I've checked https://github.com/Bill-Gray/PDCurses/blob/master/docs/HISTORY.md to know more about what is in 4.2 and am now confused about what is in 4.1 as it does not have an entry at all and its new vt port somehow slipped into 4.0.
Can you please verify and "adjust the history"?

**Comment by Bill-Gray** [comment]
I believe it's all sorted out now.  Fortunately,  we had some history from the releases,  which mentioned 4.0.2 (which went completely unmentioned in `HISTORY.md`.)
The VT backend is mentioned as being part of 4.0.4.  As a result,  4.1 is nothing but 'changes copied in from wmcbrine'.

**Comment by GitMensch** [comment]
Looks better, but the important 3.8 and 3.9 entries are now [all removed](https://github.com/Bill-Gray/PDCurses/commit/30654afe81cb8581d81f9faf35f7f650c6851960?short_path=8e38b42#diff-8e38b429d5b49af4a2e4b87d00c5cfa7). Most/all are part of either 4.1 or 4.2 aren't they?

**Comment by Bill-Gray** [comment]
True.  The problem is that 3.8 and 3.9 were basically done in parallel,  and are in William's fork but not this one.  I figured I'd just say "pulled in William McBrine's changes" and point people to his history log.

**Comment by GitMensch** [comment]
I see, but people read only the history log of the sources they have. There are two reasonable options:

* split the history file between this repo and upstream {_looks_ easier but confusing to the user[
* integrate Williams changes into this history log in exactly the version they were made available (copy the contents, to the right places with either a prefix where they are originated from or below a note where they came from) [this is what I as a user would prefer]

**Comment by GitMensch** [comment]
@Bill-Gray are you ok with reopening?

**Comment by Bill-Gray** [comment]
Yup.  (May not be able to do the actual revision in the next few days.)

**Comment by Bill-Gray** [comment]
I believe 81ec202f6cbaa8d7bfabda9ac95a05cba6130d5f fixes this.  Please reopen if you see remaining/further `HISTORY.md` problems.

**Comment by GitMensch** [comment]
Thank you for coming back to this.
I'd say that's solved now, but I left some comments on that commit, please check those for possibly cleaning it up a bit more.
