### ISSUE TITLE
Makefile confusion

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#131]
_Originally posted by @GitMensch in https://github.com/Bill-Gray/PDCurses/issues/129#issuecomment-633430369_

> Tried [to build wincon] the exact same [way] with 3.9 [as it was done with 4.2] -> not possible because there is no Makefile.mng any more (we only have this with wingui + wincon, possibly something to clean up) [...]

result of further checks

* wincon has both a "plain" Makefile and Makefile.mng (the later was removed by William)
* wingui has only a Makefile.mng and no "plain" one
* wincon's "plain" Makefile misses the CHTYPE part
* vt + wingui still build demos by default (as does wincon/Makefile.mng)
* libobj.mif + watcom.mif should be removed from root and its reference in the makefiles be adjusted to $(common)/...mif
* makedist.mif and likely version.mif should be moved to $(common), too
* `strip` in vt/Makefile misses the conditional ".exe"
* ncurses has a "makefile" and therefore stand out with the lowercase "m"

**Comment by Bill-Gray** [comment]
@GitMensch Thanks for the list.  I believe these are all fixed now... feel free to re-open if you find otherwise.
