### ISSUE TITLE
please fix appveyor integration

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#135]
The build status is not updating and the pull-requests don't show anymore if those would break/fix anything (they currently are fine).
@Bill-Gray Can you please recheck what is going on? Seems like the GitHub part is broken (you may may not be able to fix this via Appveyor), I have no idea what changed when :-(

**Comment by Bill-Gray** [comment]
I'd tried all sorts of things to get AppVeyor builds to start on push requests,  with zero success.  Yesterday,  it occurred to me to just introduce PDCursesMod as a new project in AppVeyor.  Today,  I pushed a small change to version constants,  and that appears to have set AppVeyor in motion.  I still don't know why it stopped working,  but "turning it off and turning it back on again" seems to have fixed it.
