### ISSUE TITLE
PDC4.1.99 CHTYPE_64=Y DLL in GUI mode - no displayed output.

### ISSUE THREAD

**Issue by DCWall** [Bill-Gray/PDCursesMod#152]
Bill, I've had success with CHTYPE_32 & 64 in Console mode and need to get the correct boxchars in 32 GUI mode - however 64 GUI mode is not displaying anything other than a blank box - see below.
GitMensch suggested testing the demo programs and annoyingly they work fine. Any Ideas.

![419964g](https://user-images.githubusercontent.com/24244157/83985982-845ecc00-a97e-11ea-9e74-0257954cf2e9.jpg)

I'm assuming the image has posted above.
Dave Wall

**Comment by GitMensch** [comment]
@DCWall: Is this still happening with PDCursesMod 4.2.0?

**Comment by DCWall** [comment]
Simon,

Since my wife passed in June I haven't even played with what 
I had and certainly haven't looked at any improvements.
It'll take me a month or so to get up to speed and since I 
was only messing with GnuCobol to improve old programs I had 
written for her - the incentive has rather gone away.

Simon Sobisch wrote:
> @DCWall <https://github.com/DCWall>: Is this still happening with 
> PDCursesMod 4.2.0?
>

**Comment by Bill-Gray** [comment]
I assume this is now a "fossilized" issue and will close it as "never figured out what was going on here."
