### ISSUE TITLE
to keep or not to keep (dist target)

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#164]
It was removed upstream with https://github.com/wmcbrine/PDCurses/commit/fc12fadc30f3fde5edf82529f8e7c1968469d64e - we currently have it in (but not completely functional).

I'd like to clean it up (=either moving the makedist.mif to common and at least glance over this part or removing it); but would like to need which direction to take.

@Bill-Gray what is your take on this?

**Comment by Bill-Gray** [comment]
I have never made use of this capability,  and it sounds as if William found it to be obsolete as well.  If it were working properly,  would you make use of it?  (Anyone care to say that this looks useful to them?)

If nobody is going to use it,  I'd be fine with removing it.  (Also to be considered : we have,  to one degree or another,  tried to maintain some similarity to wmcbrine/PDCurses. I'd like to keep doing that,  even if we are now "consciously uncoupled".  It makes it easier to bring in changes William makes that we happen to like,  and vice versa.)

**Comment by Bill-Gray** [comment]
Somewhere along the line,  I removed almost all of these,  except for a bit of junk in WinCon's `Makefile`.  I've just removed that as well (haven't pushed the change yet).  So... closing.
