### ISSUE TITLE
wincon Makefile LIBSADDED = -lwinmm causes compile error ar: invalid option -- w

### ISSUE THREAD

**Issue by shashfrankenstien** [Bill-Gray/PDCursesMod#182]
OS: Windows 10
Compiler: TDM-GCC-64

Attempting to compile wincon fails with the following error message - 

```
...
ar rcv pdcurses.a addch.o addchstr.o addstr.o attr.o beep.o bkgd.o border.o clear.o color.o delch.o deleteln.o getch.o getstr.o getyx.o inch.o inchstr.o initscr.o inopts.o insch.o insstr.o instr.o kernel.o keyname.o mouse.o move.o outopts.o overlay.o pad.o panel.o printw.o refresh.o scanw.o scr_dump.o scroll.o slk.o termattr.o touch.o util.o window.o debug.o pdcclip.o pdcdisp.o pdcgetsc.o pdckbd.o pdcscrn.o pdcsetsc.o pdcutil.o -lwinmm
ar: invalid option -- w
...
```

I was able to successfully compile on clearing -lwinmm from LIBSADDED flag here https://github.com/Bill-Gray/PDCursesMod/blob/f29fe060e7cacac7aa96b194b5364e46137e9f1e/wincon/Makefile#L120
but I see that it was added recently in https://github.com/Bill-Gray/PDCursesMod/commit/7fac6f618f82b6570f093ca5ef3cc3035238f437

**Comment by GitMensch** [comment]
Interesting. I'm not sure about specifying `ar` and a library together at all...

Does it work if you use the following?

```diff
- LIBSADDED = -lwinmm
+ LIBSADDED = -l"winmm"
```

What is your complete `make` command line?

**Comment by shashfrankenstien** [comment]
Same error message with the quotes.

I'm running `mingw32-make.exe -f Makefile`

**Comment by shashfrankenstien** [comment]
Fix merged https://github.com/Bill-Gray/PDCursesMod/pull/183
Thank you!
