### ISSUE TITLE
speed.c demo update suggestion

### ISSUE THREAD

**Issue by ceka** [Bill-Gray/PDCursesMod#185]
building demos on windows10 returns error:
```
speed.c
../demos\speed.c(49): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
NMAKE : fatal error U1077: 'D:\apps\vs2019\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe' : return code '0x2'
Stop.
```

resolution:

add 
```
|| defined(_MSC_VER)
```
to line: 
```
#if defined(__TURBOC__) || defined(__EMX__) || defined(__DJGPP__) || \
    defined( __DMC__) || defined(__WATCOMC__)
```

result:
```
#if defined(__TURBOC__) || defined(__EMX__) || defined(__DJGPP__) || \
    defined( __DMC__) || defined(__WATCOMC__) || defined(_MSC_VER)
#include <sys/timeb.h>
```

fortunately sys/timeb is available on Microsoft platform :)

**Comment by GitMensch** [comment]
Thank you very much  do you mind doing this in the source via GitHub? Just browse to the file below "<>code" then click on "edit" then on "save" and on "create pull request"?

**Comment by ceka** [comment]
ah, so that's how it is done. np. one sec

**Comment by ceka** [comment]
#186

**Comment by GitMensch** [comment]
That looks good, thanks. I've run the CI build on Appveyor manually (@Bill-Gray, we really should get #135 working again), but without #184 the builds there (which use CMake) don't even get to the demos. Side note: the SDL-builds are broken on win32, too - @ceka if you could try to fix these, too - this would be marvelous!

**Comment by ceka** [comment]
Do you mean sdl1 catalog ? sdl2 builds fine.

**Comment by GitMensch** [comment]
According to Appveyor SDL2 is broken: https://ci.appveyor.com/project/Bill-Gray/PDCurses/build/job/48id344y3dt9px38 - but I've just seen that #187 was supposed to fix that...

**Comment by ceka** [comment]
please see #188 only for nmake. i will check if i could do something with cmake.

**Comment by GitMensch** [comment]
I was told that cmake should be fine, let's see what [the build](https://ci.appveyor.com/project/GitMensch/pdcurses/builds/35642838) says that I've started after merging #188.
