### ISSUE TITLE
Use of PSF2 fonts; possible Linux framebuffer port

### ISSUE THREAD

**Issue by Bill-Gray** [Bill-Gray/PDCursesMod#208]
(Extension of some comments I made in re pull request #207.  As noted there,  I don't expect to be doing much on this very soon,  due to other commitments,  but it's probably well for the ideas to be written down somewhere.)

We have some nice code for use of PSF2 fonts from @chasonr's `DOSVGA` port.  These fonts could also be used in SDLn,  which currently uses a simple (but completely non-standard) format based on Windows .BMP files.  The PSF2 fonts and code could also be used in a Linux framebuffer port,  suitable for low-end and embedded systems without X;  and,  conceivably,  they could be used to replace the current X11 fonts on that platform.

I envision pulling the PSF2 code out from `DOSVGA` and putting it into the `common` directory.  One could read a font into a buffer and then call functions such as,  say, `init_psf2_font_from_buffer()`,  `get_glyph_from_buffer()` (for a particular code point),  and eventually `free_psf2_font_data()`.  One might do that four times,  to get regular,  italic,  bold,  and italic bold fonts;  possibly more often to get fallback font(s).  The same code could be used for 8-bit and wide-character builds;  the only difference would be that in the first case,  the fonts would be a lot smaller.  It does not appear to me that the refactoring would be especially difficult.

As a side benefit,  having cleanly separated functions to access PSF2 fonts could be useful in projects utterly unrelated to PDCursesMod.  I'd like to have the functions work from buffers so that if no font is specified,  we can just pass a pointer to an in-memory representation of a default font.

Once the separated font code worked with `DOSVGA`,  I would be inclined to get going on a Linux framebuffer port.  That should be fairly straightforward;  code for input would come from the VT port,  and output to the framebuffer is very easy,  once one has the PSF2 font glyphs.

At a comparable level of priority would be ripping out the odd bitmapped font format from SDLn and having it use PSF2.  The X11 port could be considerably simplified by using these fonts as well,  but I don't see that as being much of a priority,  and it probably never would be.

**Comment by GitMensch** [comment]
I guess that's work-in-progress with the current framebuffer port? I guess that would be the missing bit which leads to a 4.4 (no hurry, just asking)?

**Comment by Bill-Gray** [comment]
The framebuffer port is entirely usable at this point.  Its major shortcoming is a lack of mouse support.  There appear to be at least three ways of accessing the mouse from the Linux console (`uinput`, `gpm`,  and direct reading of `/dev/input/mice`.)  All documentation I've found on this tends to be decades old,  and I'm not entirely sure if any of these is what I "ought" to be using.

I am also in no rush for 4.4.  The framebuffer port,  significant as it is,  is the _only_ change thus far since 4.3 was released,  and I'd not consider it really 'finished' until the mouse works.  I've also heard a total of zero comments from people using it;  I'd like to have some sense that it works for others before calling it version 4.4.

I may also wait until rotation is added.  This port is likely to be used on embedded devices,  where such support matters.  In theory,  I'll be receiving a [PinePhone](https://pine64.com/product/pinephone-beta-edition-with-convergence-package/) in the next weeks,  and should be able to try it out.

**Comment by GitMensch** [comment]
>  In theory, I'll be receiving a [PinePhone](https://pine64.com/product/pinephone-beta-edition-with-convergence-package/) in the next weeks, and should be able to try it out.

That sounds quite interesting, congratulations. I'm looking forward to see how this effects the vt and framebuffer ports.
I guess there's a dev community for that where you could even now ask about how to access the touchpad of that (potentially even with gestures like zoom in/out) - which is likely the way the mouse _should_ be accessed, too. 

>  The framebuffer port, significant as it is, is the _only_ change thus far since 4.3 was released

So my question about "use of PSF2 fonts" is "that's not done so far" (would effect at least DOSVGA, too), correct?

**Comment by Bill-Gray** [comment]
The framebuffer port can use PSF1,  PSF2,  old-style "raw" VGA fonts,  or its built-in font.  It turned out that if you write code for PSF2,  the others are pretty easy to add in.

I've not gotten around to having the relevant code be used in SDLn and/or DOSVGA.  (This actually _could_ also be used in WinGUI and/or X11,  but I don't see a really good reason to do so.)  One aspect of their use in SDLn is that one could use either TrueType or PSFn fonts in either the 8-bit or wide-character versions,  i.e.,  the fonts you use don't have to have anything to do with the character bit depth.  Currently,  SDLn uses TrueType for all wide-character builds and either a Windows bitmap or a built-in bitmap for 8-bit character builds.

**Comment by Bill-Gray** [comment]
The framebuffer port works nicely,  and now can also be compiled for the Direct Rendering Manager (DRM).  I've run the latter on Linux and FreeBSD.  While I don't have all the bits mentioned in some of the 'dream list' items above,  I'd say it's done enough to close this particular issue.
