### ISSUE TITLE
windows terminal adjustments for wincon?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#211]
See [related changes from upstream](https://github.com/wmcbrine/PDCurses/search?q=pdc_wt) `pdc_wt`, similar to the conemu adjustments.

**Comment by Bill-Gray** [comment]
Done (see commits e070c7e4db56aded2bf2e479c, 7d371655c7e4febb205c, 218f0fc5651cb07e62a8,  cherry-picked from PDCurses/wmcbrine;  commits cd22951904f655388ac529d5, 3aacf1516dd26c8bf2955a are tangentially relevant as well.)
