### ISSUE TITLE
key modifier problem

### ISSUE THREAD

**Issue by fanfan70** [Bill-Gray/PDCursesMod#217]
Trying to get key modifier flag in console (ctrl-alt-F1 from X session) but no luck. The modifier flag in the code below is always 0.
I have tried fb ant vt platforms. What am I doing wrong ?
Thank you !

test code (please find makefile after it) :
```
#include <iostream>
#include <curses.h> // getch
#include <fstream>
#include <cstring>

using namespace std;

int main( int argc, char **argv )
{
   char *term = getenv( "TERM" );
   bool isTerminal = term != nullptr && strcmp( term, "linux" ) == 0;
   if ( !isTerminal )
   {
      cerr << "run in console !" << endl;
      exit( 1 );
   }

   initscr();
   cbreak(); // allow ctrl-C to terminate app
   nodelay( stdscr, true ); // non blocking getch()
   keypad( stdscr, true ); // function keys, arrow keys, ..
   noecho(); // do not echo typed key on screen

   bool cont = true;
   while ( cont )
   {
      int ret = getch( );
      unsigned long mod = PDC_get_key_modifiers();

      switch ( ret )
      {
         case ERR:
            break;

         case 27: // esc
            cont = false;
            break;

         default:
            cout << "key " << ret << endl;
            cout << "mod " << mod << endl;
            break;
      }
   }

   endwin();
}
```

makefile :

```
# PDCursesMod config

PDMOD_DIR := PDCursesMod
#PDMOD_PLATFORM := fb
PDMOD_PLATFORM := vt
PDMOD_LIB := libpdcurses.a

pdmod_inc_dir := $(PDMOD_DIR)

# application config

SRC_DIR := src
INC_DIR := inc
BUILD_DIR := build
EXE := test-pdcursesmod
CFLAGS := -c -g -Iinc -I$(pdmod_inc_dir)
LDFLAGS += -L$(BUILD_DIR) -lpdcurses

# special makefile variable : prerequisites search path
VPATH := $(shell find $(SRC_DIR) -type d)

SOURCES := $(shell find $(SRC_DIR) -name "*.cpp" -exec basename {} \;)

TMP := $(shell echo $(BUILD_DIR) | sed "s/\//\\\\\//g")
SED :=  "s/\(.*\)/$(TMP)\/\1/g"
OBJS := $(shell echo $(SOURCES:.cpp=.o) | tr ' ' '\n' | sed $(SED))

.PHONY : $(BUILD_DIR)

all : pdmod-lib build-exe

build-dir : $(BUILD_DIR)
	test -d $< || mkdir -p $<

$(BUILD_DIR)/%.o : %.cpp
	$(CXX) $(CFLAGS) -o $@ $<

#--- exe ---

build-exe : build-dir $(BUILD_DIR)/$(EXE)

$(BUILD_DIR)/$(EXE) : $(OBJS)
	$(CXX) -o $@ $^ $(LDFLAGS)

#--- git clone ---

git-clone : $(PDMOD_DIR)
$(PDMOD_DIR) :
	git clone https://github.com/Bill-Gray/PDCursesMod

#--- build PDModCurses lib ---

pdmod_lib_path := $(PDMOD_DIR)/$(PDMOD_PLATFORM)/$(PDMOD_LIB)

build-pdmod-lib : git-clone $(pdmod_lib_path)
$(pdmod_lib_path) :
	cd $(PDMOD_DIR)/$(PDMOD_PLATFORM); make

pdmod-lib : build-dir build-pdmod-lib $(BUILD_DIR)/$(PDMOD_LIB)
$(BUILD_DIR)/$(PDMOD_LIB) :
	cp $(pdmod_lib_path) $(BUILD_DIR)


#--- cleanup ---

clean :
	rm -rf $(BUILD_DIR)
```

**Comment by fanfan70** [comment]
Thank you for the answer !
If you know a (simple) workaround in case you prefer not going in that direction... anyway I'm not in a hurry if you decide to modify your code :-)
Regards.

**Comment by Bill-Gray** [comment]
Just pushed commit 3eaab651966380ba62275ca to fix this.  We do still have the problems mentioned above : if Caps-Lock is on,  hitting Shift-B will cause `getch()` to return a lowercase 'b' with the `PDC_KEY_MODIFIER_SHIFT` flag _not_ set,  and hitting B will get (uppercase) 'B' with that flag set.  Shift-F2 will get you `KEY_F14` and that flag set;  if somebody has an old-style keyboard with a physical F14 key,  they'd get that same result when they hit that key,  even without the shift key pressed.

Short of attempting lower-level key access,  I think we're stuck with this (i.e.,  we just can't tell "exactly" what keys were hit).  I don't think it'll be much of a problem.  It should at least be an improvement over our current situation,  in which the key modifier flags were never set.

I thought I might steal ideas from ncurses on this,  but ncurses neatly sidesteps the entire problem by the subtle trick of not returning key modifier flags.  Maybe that was a good idea.

**Comment by fanfan70** [comment]
Hello,
Got your answer, I'll test it in a while and report.
Thanks :-)

**Comment by fanfan70** [comment]
Hello,
Control, shift and alt modifiers are detected through PDC_get_key_modifiers(). The code returned by getch() is different for the same physical key with or without modifiers (probably normal). For some combinations (arrow keys, suppr, insert), modifiers are not detected.
Thanks for the fix.

**Comment by GitMensch** [comment]
So - can this be closed now?

**Comment by Bill-Gray** [comment]
Yeah,  I think it can be closed.  I did have some hopes of a better solution,  probably involving lower-level access to the keyboard.  (Still would like to do that,  and similarly for the mouse;  we don't get _any_ mouse input on the Linux console,  for either VT or fb.)  But it's fair to say we've fixed this issue,  even if there is room for improvement.
