### ISSUE TITLE
INTENTIONALLY_UNUSED_PARAMETER - shouldn't that be in curspriv.h?

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#220]
... just wondering. Note: it will obviously also make it much easier to adjust this for other compilers, if necessary.

**Comment by Bill-Gray** [comment]
It _is_ in `curspriv.h`,  and all PDCurses internals use it from there.  The demos don't use PDCurses internals and therefore don't #include `curspriv.h`.

As you note,  that means that if we someday run into a compile that should have a different `INTENTIONALLY_UNUSED_PARAM` #define,  it'll have to be changed in (currently) eight demo programs _and_ in `curspriv.h`.  I didn't want to create an entirely new include file just for this one macro definition.  Though if we eventually have
```c
#ifdef __ODDBALL_COMPILER_A__
   #define INTENTIONALLY_UNUSED_PARAM( param)    something_weird
#else
   #ifdef __ODDBALL_COMPILER_B__
      #define INTENTIONALLY_UNUSED_PARAM   something_even_weirder( param)
   #else
       #define INTENTIONALLY_UNUSED_PARAM( param) (void)(param)
   #endif
#endif
```
   I'd revisit that idea.  But for a simple one-liner,  this ought to be fine.  I don't think anything should include `curspriv.h` unless it's truly accessing private internals of PDCurses.
