### ISSUE TITLE
MinGW: adding lib prefix, possibly conditional

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#222]
This suggestion is related to https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-pdcurses/001-mingw-pdcurses-4.1.0-build.patch and likely came up before:

Wouldn't it be reasonable to either "always" or "depending on a make flag" rename the targets to libpdcurses.a / libpdcurses.dll.a libpdcurses.dll?

If we need a flag then this could be "LIBPREFIX=Y" or "STDLIBNAME=Y" or similar (the later would also match to say libpdcurses.dll.a in case of an import library).

@wmcbrine likely has an opion about it, I'd like to hear is thoughts, too (because ideally we end with a solution that can be included in both projects).

**Comment by GitMensch** [comment]
The question

> Wouldn't it be reasonable to either "always" or "depending on a make flag" rename the targets to libpdcurses.a / libpdcurses.dll.a libpdcurses.dll?

is still open; current patch in MSYS2: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-pdcurses/001-mingw-pdcurses-4.3.1-build.patch; to be correct this has to be added to a bunch of the other ports, too (it _partially_ is that way unconditionally in other ports).

**Comment by GitMensch** [comment]
Yes, those changes get the point across, and in general the approach with "then change from outside" seems reasonable and better than the hard-wired one, also because it allows to "ship old result by default"!

But there's one main difference - the current patchset has an import library name of libpdcurses.dll.a and I think that's good - because it allows to build and distribute both a static and a shared version (which in your files is not possible because both import libraries are named pdcurses.a). In this specific case I'd also find a possible breakage ok.

>  If so, I'd be perfectly happy to push these changes.

That would be cool, especially when applied to all Makefiles, that would close another issue and would - with the next release - allow to drop that patch (either completely or all but the "pdcurses.dll.a" part).

**Comment by Bill-Gray** [comment]
Hmm... so we'd actually want the ability to set `LIBNAME=myrandomname.dll.a DLLNAME=myrandomname.dll` when building the shared-library version,  and then set `LIBNAME=myrandomname.a` for the static one?  I.e.,  use separate variables so that both import library and shared library can be named independently of one another;  some might set `LIBNAME=pdc_shared.a` and `LIBNAME=pdc_static.a` to generate separate import libraries.

[I've modified the previously modified `makefile` for WinCon to show how this would work.](https://www.projectpluto.com/temp/wincon/Makefile)  I just tried it with `LIBNAME=able DLLNAME=baker` and got `able.a` and `baker.dll`.

**Comment by GitMensch** [comment]
Sounds good, but should be documented on top under "usage" - otherwise fine.

**Comment by Bill-Gray** [comment]
Added a usage statement and made similar `LIBNAME`/`DLLNAME` changes for WinCon,  WinGUI,  VT,  SDLn,  and framebuffer.  X11 will,  I think,  be trickier.  Haven't got round yet to DOS,  DOSVGA,  or OS/2 (testing those is the real problem).  Feel free to close this if it does what you're looking for on your end.

**Comment by GitMensch** [comment]
The platform changes so far look good.

XCurses uses a configure script, there is nothing to change there.

It would be good if DOS* could be adjusted similar (can't those be tested relative easily with a FreeDOS environment?) ... and only leaving OS/2 open seems bad.
Are any of those used in the CI built?

**Comment by GitMensch** [comment]
Of course, I've did it wrong on the first try: `DLLNAME=libpdcurses.dll LIBNAME=libpdcurses.dll.a` - ending with `libpdcurses.dll.dll` and `libpdcurses.dll.a.a` because the extension is added automatically.
Would it be likely that more people get it as wrong as me, or would it be more likely that people would miss to add the extension if it isn't automatically added?

**Comment by Bill-Gray** [comment]
Not sure which is more likely.  But I think I'd prefer to do it the way you attempted : "I have particular filenames and extensions in mind,  and I don't want some silly Makefile tacking on extensions I didn't write.  Especially if the extension it adds on wasn't the one I wanted."

**Comment by GitMensch** [comment]
Can I ask you to make this change and also fix my partial attempt to fix vt? (I've missed the explicit "lib"-prefix for non ".exe"), note: this was different from beginning - always using a "lib"prefix, while the others didn't. I definitely would prefer the default being identical in all ports...
The vt port actually shows the nice issue that that LIBNAME default should consider .so and .dylib, too.

**Comment by GitMensch** [comment]
As this is "80% done" I suggest to handle that as last thing to do before the release ;-)

**Comment by GitMensch** [comment]
I _think_ that is done, if not we can re-open it.
