### ISSUE TITLE
VT port, Enter key and ^M returns ^J

### ISSUE THREAD

**Issue by rexx-org** [Bill-Gray/PDCursesMod#225]
Using testcurs "Input Test", pressing either Enter key or ^M all return ^J. ^J also returns ^J.  Enter keys and ^M should return ^M.
I get these results on Debian  and Alpine Linux virtual terminals. Also get same result running testcurs in xterm.

**Comment by Bill-Gray** [comment]
Hi Mark -- ugh,  I see what you mean;  I also get ^J returned when hitting Enter,  Ctrl-J,  or Ctrl-M,  also in virtual terminals and in xterm.

I may be wrong about this,  but I don't think there is a straightforward way around this.  There's no particular control over what comes from the terminal,  and what you get is dumbed down quite a bit.  I'd like,  for example,  to know when Alt or Shift or Ctrl are hit separately.  My current keyboard has a row of buttons such as "browser back",  "stop",  "refresh",  "play/pause",  etc.;  none of them return anything.  I got interested in avoiding such limitations a while back,  but didn't get far.

All this,  by the way,  also applies to the framebuffer port,  which uses essentially the same code.

I _think_ it may be possible to access the keyboard at a lower level using the [evdev library](https://en.wikipedia.org/wiki/Evdev).   This works at a rather low level,  and (if I'm understanding it properly) would mean you could use it without requiring X to be running.  However,  I think it may return keycodes;  you'd know which physical key was hit,  but knowledge of the layout (US,  Dvorak,  etc.) is handled at a higher level.

But it may be that this is the only way for a console program to really know which keys are being hit,  and (specifically) to tell a Ctrl-J from a Ctrl-M from an Enter from a keypad Enter.

**Comment by rexx-org** [comment]
You can change the behaviour with stty. Run: 
stty -icrnl
before running testcurs and you will get the correct behaviour; at least the Enter keys and ^M return ^M and ^J returns ^J.
I haven't looked yet, but there may be an ioctl call to set this on when PDCurses starts and turns it off (or leaves it alone) on exit.

**Comment by rexx-org** [comment]
As you already use termios, I added the flag to turn off ICRNL in  PDC_reset_prog_mode( void)
...
    tcgetattr( STDIN, &orig_term);
    memcpy( &term, &orig_term, sizeof( term));
    term.c_lflag &= ~(ICANON | ECHO);
    term.c_iflag &= ~(ICRNL);
...

**Comment by Bill-Gray** [comment]
Well,  I thought that might take years and cost millions of lives.  Nice to see it resolved in one tidy,  easily understood line of code... thank you!
