### ISSUE TITLE
Color number 8 is black instead of grey

### ISSUE THREAD

**Issue by Lyle-Tafoya** [Bill-Gray/PDCursesMod#229]
The 256 color palette I am familiar with uses grey for color 8, but with the SDL2 or WinGUI versions of PDCursesMod I find color 8 to be black instead. Using wincon produces the expected grey color. I thought that might be because of the difference in number of colors supported. However, I tested it on Linux with the vt build in an environment where COLORS == 16777472 (ie. konsole) and the issue was not reproducible there. Given that color 0 and color 16 are already black, I can't think of a good reason for color 8 to also be black.

I encountered this issue while trying to port my fork of the 1987 roguelike "Omega" to Windows (it uses that color for all the walls and some other things, so it's pretty noticeable when it is black instead of grey). In order to work around this issue in SDL2 PDCursesMod, I can redefine the color using `init_color(8, 500, 500, 500)`

**Comment by Bill-Gray** [comment]
It appears there's no real guarantee with curses as to what colors you'll get by default.  MANUAL.md says "`start_color()` initializes eight basic colors (black, red, green, yellow, blue, magenta, cyan,  and white)".  And,  of course,  there may not be any further colors.  The Linux console,  for example,  usually gives you eight colors.

However,  I also can't come up with a reason why color 8 should default to black.  In most palettes,  color 8 is half intensity (RGB=0x808080),  color 7 is brighter (0xA0A0A0 or 0xC0C0C0),  color 0 is straight black and 15 is RGB=0xffffff.  I've gone with that choice.

**Comment by Lyle-Tafoya** [comment]
I'm curious whether A_BOLD comes with any real guarantees regarding it's behavior though. Apparently, Omega does not have any color pairs which directly make use of color 8. In order to obtain grey foregrounds, Omega combines COLOR_BLACK with A_BOLD. More accurately, this seems to actually produce color 8 (in both ncurses and PDCursesMod). It seems that colors 0-7 combined with A_BOLD are the same thing as colors 8-16 and are even subject to redefinitions of colors 8-16 with init_color. For example, redefining color 8 as `init_color(8, 0, 1000, 0)` would result in green when combining COLOR_BLACK (as a foreground color) with A_BOLD.

In any case, I tested the latest commit and it seems to work on my end. It is no longer necessary for me to redefine color 8 to obtain grey (although, perhaps it wouldn't hurt me to explicitly redefine all used colors in environments which allow that)
