### ISSUE TITLE
DOS port fails to compile with Borland C 5.02 for DOS, even with OLD_BCC set.

### ISSUE THREAD

**Issue by johnsonjh** [Bill-Gray/PDCursesMod#233]
As I mentioned in https://github.com/Bill-Gray/PDCursesMod/issues/232#issuecomment-1073051026, some changes were needed to build on Borland C 5.02 for DOS, even with `OLD_BCC` set, because some stdint types seem to have snuck in. 

Here was my quick & dirty workaround:

```diff
diff --git a/pdcurses/color.c b/pdcurses/color.c
index 92fd889e..cc76f7b3 100644
--- a/pdcurses/color.c
+++ b/pdcurses/color.c
@@ -178,21 +178,21 @@ static void _link_color_pair( const int pair_no, const int head)
 {
     PDC_PAIR *p = (PDC_PAIR *)SP->atrtab;
     PDC_PAIR *curr = p + pair_no;
 
     curr->next = p[head].next;
     curr->prev = head;
     p[head].next = p[curr->next].prev = pair_no;
 }
 
 #if PDC_COLOR_BITS < 15
-    typedef int16_t hash_idx_t;
+    typedef short hash_idx_t;  /* XXX(jhj): stdint type */
 #else
     typedef int32_t hash_idx_t;
 #endif
 
 static hash_idx_t *_pair_hash_tbl = NULL;
 static int _pair_hash_tbl_size = 0, _pair_hash_tbl_used = 0;
 
 static int _hash_color_pair( const int fg, const int bg)
 {
     int rval = (fg * 31469 + bg * 19583);
diff --git a/pdcurses/util.c b/pdcurses/util.c
index 6e5a6ceb..37c02344 100644
--- a/pdcurses/util.c
+++ b/pdcurses/util.c
@@ -116,21 +116,21 @@ void use_env(bool x)
     PDC_LOG(("use_env() - called: x %d\n", x));
 }
 
 int delay_output(int ms)
 {
     PDC_LOG(("delay_output() - called: ms %d\n", ms));
 
     return napms(ms);
 }
 
-int PDC_wc_to_utf8( char *dest, const int32_t code)
+int PDC_wc_to_utf8( char *dest, const long code) /* XXX(jhj): stdint type */
 {
    int n_bytes_out;
 
    if( code < 0)
        n_bytes_out = 0;
    else if (code < 0x80)
    {
        if( dest)
            dest[0] = (char)code;
        n_bytes_out = 1;
```
(Sorry it's not a proper patch, I'm posting from a phone currently.)

**Comment by Bill-Gray** [comment]
I have BCC-5.5,  which doesn't actually compile for DOS targets (5.02 was the last version to do that.)  I'd forgotten about that;  compilation went smoothly right until it got to DOS-specific interrupt handling code.  But that did get far enough to choke on the cases you mention,  so I _almost_ got a fix posted before you even opened the issue.  Not quite,  though.

Turns out I can build the OS/2 code,  including the demos,  using OpenWATCOM from DOSBox.  It seems a little weird to build OS/2 code from DOS emulation on a Linux box.

**Comment by johnsonjh** [comment]
> Turns out I can build the OS/2 code, including the demos, using OpenWATCOM from DOSBox. It seems a little weird to build OS/2 code from DOS emulation on a Linux box.

Yes, it's weird and clunky, for sure.

I mostly set it up because I wanted to start with a known working configuration for the Phar Lap 286|DOS-Extended SDK, which comes with support for DOS Borland C and DOS MSC (including precompiled libraries, compiler drivers, and linker wrappers). I worked though all the provided example code and verified it was working. From there, I was able to get it work with OpenWatcom 2 (and had a good point of reference and known working executables to compare against.)

As for the fix, https://github.com/Bill-Gray/PDCursesMod/commit/9220ca87dd29bc534b48e6f21d906a6cca114f7a looks good, I can test and confirm the fix tonight and close the issue, but, since I can't imagine why it wouldn't work, you can close and I'll just reopen if need be.

**Comment by johnsonjh** [comment]
@Bill-Gray I confirm this is now resolved, so I'll close this issue.

Thanks for the quick response.
