### ISSUE TITLE
Add it to vcpkg?

### ISSUE THREAD

**Issue by malvarco** [Bill-Gray/PDCursesMod#242]
I like that PDCurses 3.9 can be integrated in MS Visual Studio projects easily using Vcpkg.
Could PDCursesMod  be added to Vcpkg list as well?

**Comment by GitMensch** [comment]
This is something to check with the vcpkg package team, please post it [there](https://github.com/microsoft/vcpkg/issues/new/choose).
... checking its issue tracker leads to https://github.com/microsoft/vcpkg/issues/14620, you may want to reference that.

And yes: there is no problem (concerning "us") to add it there, in any case it will likely be useful to add different ports there, too (including not only Win32); but that's up to the vcpkg team. If there are questions we may be able to help.

Using the cmake option _may_ be useful for them (it is used by the nightly builds so should work fine).
