### ISSUE TITLE
tigetstr function is not library (PDCurses for VT)

### ISSUE THREAD

**Issue by okbob** [Bill-Gray/PDCursesMod#253]
I did `vt` build on linux. And although terminfo.c is part of PDCursesMod, this file was not compiled and linked. Unfortunately my app `pspg` was not linked due missing tigetstr function.

**Comment by GitMensch** [comment]
This was deleted "upstream" for PDCurses 3.9, the same was applied here in 22c4d82f8cd370d7af7ee805de4b4adc3e95ce1e, then re-added later with d5d2d8a857dba7732e61c5317b493219a1b0f26b - but was not added back to the Makefiles and other places.

You may want to check if applying https://github.com/Bill-Gray/PDCursesMod/pull/254 helps.

**Comment by okbob** [comment]
yes, this issue is fixed now in master branch. Thank you
