### ISSUE TITLE
WINCON: Is not capable of displaying unicode above 0xFFFF

### ISSUE THREAD

**Issue by okibcn** [Bill-Gray/PDCursesMod#272]
WINCON is not capable of displaying unicode codepoints above 0xFFFF. It is caused by the assumption that a widechar for Windows32 API is like a unicode. But, the Win32 API wchar is a WORD, and requires two wchar units encoded in UTF-16 for the API to properly display it.

**Comment by okibcn** [comment]
I have created [pull request 273](https://github.com/Bill-Gray/PDCursesMod/pull/273) to solve the issue.

**Comment by GitMensch** [comment]
close-fixed by 3ec63c906751696986c97c27f1fea6efaacfe29d
