### ISSUE TITLE
Input is not working for codepoint entries above 0xFFFF

### ISSUE THREAD

**Issue by okibcn** [Bill-Gray/PDCursesMod#274]
When using the new Windows 11 tool for inserting special characters such as emojis, PDCursesMod cannot handle the input correctly. It all comes from the fact that Win32 API handles UTF-16 units, and sometimes a wchar_t (Unicode) requires more than one unit from the OS.

**Comment by okibcn** [comment]
I have added a new [commit](https://github.com/Bill-Gray/PDCursesMod/pull/273/commits/7e28f97cf158c33bf4944beab19d9e09a6ef3277) to https://github.com/Bill-Gray/PDCursesMod/pull/273 that solves the issue.

**Comment by GitMensch** [comment]
Fixed with 3ec63c906751696986c97c27f1fea6efaacfe29d.
