### ISSUE TITLE
[BUG] PDC_get_key_modifiers() doesn't work properly in WINCON.

### ISSUE THREAD

**Issue by okibcn** [Bill-Gray/PDCursesMod#275]
The modifiers are reset every time we ask for a new key event, even when there is no new key event. PDC_get_key_modifiers() should retain the modifiers of the last key event. So, without a new key event, the modifiers should remain.

This only happens with wincon. wingui works properly.

**Comment by GitMensch** [comment]
close-fixed by 9229f08604b47627ed6a4cdf20bf84e8aa519608
