### ISSUE TITLE
[WINCON]: Transparent background in enabled terminals doesn't work in ANSI mode.

### ISSUE THREAD

**Issue by okibcn** [Bill-Gray/PDCursesMod#279]
The way the color setup is applied removes the possibility for console apps such as Windows Terminal to properly display transparent/acrylic/image backgrounds. This is a bug in how colors are applied in the ANSI mode of wincon environment, as it works well when not using ANSI mode.

A solution is proposed in Pull request [273](https://github.com/Bill-Gray/PDCursesMod/pull/273), commit [6e0d482](https://github.com/Bill-Gray/PDCursesMod/pull/273/commits/6e0d48229ddc169e90e749b26dc2f8da8e981940).

See comparison:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/22417711/218614827-0d4551d0-d2d0-4398-aeb7-d06292d1920c.png">
Left: Current version;  Right: proposed commit.

**Comment by GitMensch** [comment]
as the related PR was closed as "already cherry-picked" I consider this closed-fixed by 81cbefbd4bcf0957efb94ad8bd81dd9a60322bd4
