### ISSUE TITLE
wingui + likely SDL: demos are command line programs

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#291]
Checking the wingui demos from Appveyor shows that the compile of those is not different than on wincon and starting those with double-click lead to a cmd starting, which starts the demo program.

I _guess_ it would be fine to add a `WinMain` to all of these that is wrapped with a bunch of defines, so that wingui, *sdl* will use this (and an include of windows.h) on WIN32 during compile.

**Comment by Bill-Gray** [comment]
`newtest` has the added code in it to be compiled with a `WinMain()`,  just to demonstrate how it's done [(see comments and code here)](https://github.com/Bill-Gray/PDCursesMod/blob/4f3dc9643601d037640f4ce2e3370758aca01eb9/demos/newtest.c#L107).  I've never seen any real need to repeat the process for the other demos.

**Comment by Bill-Gray** [comment]
As noted above,  we do have an example (`newtest`) showing how to get a cmd-less WinGUI program to work.  That should be enough.
