### ISSUE TITLE
inspect DosBox sdl2_queue for sdl2 and gl

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#293]
I'm not sure yet, but it may be reasonable to pick some of the changes in https://github.com/dosbox-staging/dosbox-staging/commits/main/src/libs/PDCurses/sdl2_queue and place them into PDCursesMod (some are already in different like the INTENTIONALLY_UNUSED), possibly as a build time option (define), for example the HighDPI mode

@Bill-Gray  @juliusikkala

**Comment by juliusikkala** [comment]
HighDPI stuff seems reasonable. I'm not sure if the event queue they're doing is necessary, though. I assume it's to fix the jittery mouse inputs in the SDL2 port. I actually **_didn't_** copy `PDC_pump_and_peep` from the sdl2 port to the gl port. The one in gl fixes the jittery inputs: https://github.com/Bill-Gray/PDCursesMod/blob/52a2fdf518d29fe80078fa1a18afd91c3831cb15/gl/pdcdisp.c#L911-L928

The `SDL_PushEvent` approach shuffles the inputs around a bit. By peeping the event first, it's possible to keep SDL2's internal event queue undisturbed even if the event isn't consumed in `PDC_pump_and_peep`. This way, there's no need to keep a duplicate event queue on our side.

**Comment by GitMensch** [comment]
Hm, now I do wonder if this event handling shouldn't be done in "our" sdl2 port, similar to the new version in the "gl" one...

Depending on the "possible breakage" this may need to wait after the next release, but i have nearly zero SDL knowledge, so cannot judge that.

**Comment by GitMensch** [comment]
another ping @Bill-Gray

**Comment by GitMensch** [comment]
we may should close this as unplanned...

**Comment by Bill-Gray** [comment]
Can't say I plan to do it (at least,  not any time soon),  and it sounds as if you don't either.  So yes,  I'll close it.

I should probably put together a list of things I _am_ thinking of working on,  should I ever have time to do so.  (Which won't happen soon;  the point of the list would mostly be to remind myself,  possibly years from now,  that these would be interesting things to do.)  A few things that leap to mind,  in no particular order :

- I learned a bit about X11 recently that makes me think I may be able to drastically simplify that platform.  It's pretty complicated at present (i.e.,  I don't understand most of it).
 - It would be nice if the VT (and maybe Windows console) platforms could,  optionally,  open up in a separate terminal window and display within them;  you could then still do `printf`s and such in the terminal within which you're running.
-  I'm thinking about ways of enabling multi-screen displays (i.e.,  use `newterm()` multiple times to open the multiple terminal windows,  and then use [set_term()](https://invisible-island.net/ncurses/man/curs_initscr.3x.html) to switch between the resulting displays).
- SDL1,  SDL2,  and GL have a heck of a lot of identical (or nearly identical) code that ought to be ripped out and put into the `common` directory.
- Those three libraries also use a really weird font format,  based on Microsoft Windows .BMP files,  when running in 8-bit mode.  I'd kinda like to take the PSF handling code from the framebuffer/DRM code,  put that into the `common` directory,  and use it on those platforms.
- The framebuffer/DRM port now displays combining characters,  but is ignorant of fullwidth characters.
- The framebuffer/DRM port still doesn't handle the mouse.  But I've learned a bit recently about the `/dev/input/event*` system,  which allows full access to the mouse from the Linux console.  So I now know how to do it;  it's just a matter of putting the pieces together to add mouse support to that platform.
