### ISSUE TITLE
PDCursesMod 4.4.0 (breaking binary compatibility)

### ISSUE THREAD

**Issue by Bill-Gray** [Bill-Gray/PDCursesMod#299]
I've had a few changes in mind that would break binary compatibility.  These would cause us to go from the 4.3 series to a new minor version number,  4.4.  [Changes that break binary compatibility would be reflected in `curses.h` so as to prevent accidental linking to an incompatible library.](https://github.com/Bill-Gray/PDCursesMod/blob/c51e0fb5cc27d7dabd0f0d7facb78ab135d35dd0/curses.h#L38)

I'd want 4.4 to collect any "dangling issues/ideas/improvements" that break binary compatibility.  The purpose of this issue is largely to ask if anybody has further issues/ideas/improvements to suggest.

The binary compatibility-breaking changes I currently have in mind are : 

- Make the `SCREEN` and `WINDOW` structs private. As the [`opaque_screen`](https://github.com/Bill-Gray/PDCursesMod/tree/opaque_screen) fork illustrates,  this is quite easy to do.  It would mean that further alterations to those structures could be done without breaking binary compatibility,  and would help discourage people from relying on (completely non-portable) access to elements from these structures.
- Raise `KEY_MAX` to a value allowing us to keep some reserved key codes.  I've considered adding `KEY_FOCUS_IN` and `KEY_FOCUS_OUT` key codes,  to be sent when a screen receives or loses the focus,  but can't really do that safely at present.  (This may also result in a `PDC_focus()` function,  which would indicate if the screen does or does not have the focus,  or if that fact cannot be determined.  For example,  on the VT platform,  we don't actually know if the window has the focus until the status changes.  Under DOS,  for example,  you'd always have the focus.)
-  [X/Open says the `WA_ATTR*` #defines are supposed to be distinct](https://pubs.opengroup.org/onlinepubs/7908799/xcurses/curses.h.html);  in PDCurses*, they are not.  Doing so would require fifteen bits for these attributes,  plus a sixteenth for the PDCursesMod extension `WA_STRIKEOUT`.  (And I see now that we have `A_STRIKEOUT`,  but not `WA_STRIKEOUT`).  This can be done trivially for 64-bit `chtype`s.

We actually could keep the `WA_ATTR*`s distinct for 32-bit `chtype`s (or even 16-bit `chtype`s if we wanted to go full-retro),  but only by requiring `chtype` to no longer equal `attr_t`.  That would involve considerable pain for minor benefit.

Note that these changes are pretty trivial to implement,  and I'd normally not comment on them... except for the fact that they require a new minor version number.

**Comment by Bill-Gray** [comment]
The changes have been made,  tested,  and 4.4 pushed to GitHub,  so I'm closing this.

**Comment by GitMensch** [comment]
> 4.4 pushed to GitHub

There isn't a tag/release yet, do you want to do that soon?

**Comment by Bill-Gray** [comment]
I'd be fine with doing a tag/release.  The release schedule is basically "when somebody asks."

4.4.0 gives us a better match to specifications.  The `SCREEN` and `WINDOW` structures are specified to be opaque;  they now are.   The `attr_t` masks are specified to be distinct;  they now are.  This is all nice stuff,  and there are also a few bug fixes.  But thus far,  none of it has caused anybody to say to me,  "I could use that;  please do a tag/release."
