### ISSUE TITLE
undocumented compatibilty break wincon/wingui

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#300]
wincon allows to maximize the screen, while wingui seems to be either fixed-maximized (but that _seems_ to be only be done when the registry was written outside of the application) or "not maximizable".

Please document the difference and in general the registry storage.

**Comment by GitMensch** [comment]
friendly ping @Bill-Gray

**Comment by GitMensch** [comment]
friendly ping @Bill-Gray

**Comment by Bill-Gray** [comment]
Revised to make the windows resizable,  same as in most other platforms (except DOS,  DOSVGA,  framebuffer/DRM,  etc.,  where you can't resize anyway).  Such was the original behavior,  and it really makes more sense anyway.
