### ISSUE TITLE
SDL2 build fails for Mac/Linux in Github

### ISSUE THREAD

**Issue by Bill-Gray** [Bill-Gray/PDCursesMod#302]
(Was issue wmcbrine/155) Quoting @pavkam from that issue : 

-----------------------
Not entirely sure what is causing it:

Example of failed build:
https://github.com/pavkam/sharpie/actions/runs/6369436403/job/17289688889
```
Makefile:60: *** Recursive variable 'CC' references itself (eventually).  Stop.
```
It works for other platforms (arm + win).

The build steps I use are here:
https://github.com/pavkam/sharpie/blob/main/.github/workflows/pd-curses-mod-build-and-pack.yml#L101

**Comment by Bill-Gray** [comment]
Sorry,  I _thought_ I 'd posted a possible fix here immediately after moving the issue!

The error message is accurate.  By default,  `$(CC)` is defined in terms of `$(PREFIX)`,  which in turn is defined in terms of `$(CC)`.  That's recursive,  all right.

On ARM and Windows,  `$(PREFIX)` is _not_ defined using `$(CC)`,  so there's no recursion.

It seems to me that all we need to do is to remove from `sdl2/Makefile` the line
```
PREFIX = $(shell $(CC) -dumpmachine)
```
and add in
```
ifdef _w32
   PREFIX=i686-w64-mingw32
   E = .exe
endif
```
   The line we'd be removing was added by @okibcn,  and I'm not entirely sure why it's there... @okibcn,  any comment?

**Comment by GitMensch** [comment]
Possibly different MSYS2 variants? In this case there are also matching environment variables for that.

**Comment by Bill-Gray** [comment]
Note that this is a duplicate of #296.  I think this is now fixed,  and am closing both issues.
