### ISSUE TITLE
Add shared option for all variants

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#87]
Currently only wincon + win32a have DLL options (and not for all makefiles).
Can you please add shared options for the others (for SDL/SDL2/X11/VT this is also interesting on GNU/Linux environments where a "fat" static library is the only option using the current Makefiles).

**Comment by Bill-Gray** [comment]
We already had shared libraries in X11,  and now have them on the SDLs (commit b78cd8a33f9d552df4a3a06ce65),  VT (commit d0309c296351d3ddf1d3d594f5114ea),  and framebuffer ports.  I think this issue got gradually solved without my noticing that there was a closable issue.
